trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'
  demands:
    - agent.name -equals AgentSelfHosted

variables:
  system.debug: true

stages:
- stage: BuildAndTest
  displayName: Build and Test
  jobs:
  - job: BuildAndTest
    displayName: Build and Test Application
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'  # Node.js 18 or higher
      displayName: 'Install Node.js'

    - script: |
        node -v
        npm -v
      displayName: 'Verify Node.js and npm Versions'

    - script: |
        npm install -g @angular/cli
      displayName: 'Install Angular CLI'

    - script: |
        cd front-end  # Adjust if your folder path differs
        npm install --frozen-lockfile
        npm run build --prod
      displayName: 'Build Frontend'

    - script: |
        cd front-end  # Ensure you're in the correct directory
        ng test --watch=false --browsers=ChromeHeadless
      displayName: 'Run Tests'



- stage: Package
  displayName: Package Docker Image
  jobs:
  - job: Package
    displayName: Package Docker Image
    steps:
    - script: |
        docker build -t $(containerRegistry)/$(imageRepository):$(Build.BuildId) .
        docker push $(containerRegistry)/$(imageRepository):$(Build.BuildId)
      displayName: 'Build and Push Docker Image'