trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'
  demands:
    - agent.name -equals AgentSelfHosted

variables:
  system.debug: true
  containerRegistry: 'registry0'
  imageRepository: 'projetweb'

stages:
- stage: BuildAndTest
  displayName: Build and Test
  jobs:
  - job: BuildAndTest
    displayName: Build and Test Application
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'  # Node.js 18 or higher
      displayName: 'Install Node.js'

    - script: |
        node -v
        npm -v
      displayName: 'Verify Node.js and npm Versions'

    - script: |
        npm install -g @angular/cli
      displayName: 'Install Angular CLI'

    - script: |
        cd app  
        npm install --frozen-lockfile
        npm run build --prod
      displayName: 'Build Frontend'

    - script: |
        cd app  
        ng test --watch=false --browsers=ChromeHeadless 
      displayName: 'Run Tests'


- stage: DockerBuildAndPush
  displayName: Docker Build and Push
  dependsOn: BuildAndTest  
  jobs:
  - job: DockerBuildAndPush
    displayName: Build and Push Docker Image
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: $(containerRegistry)  
        #repository: $(imageRepository) 
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'  
        tags: '$(Build.BuildId)' 
      displayName: 'Build and Push Docker Image'
    - script: |
        echo "Running custom Docker Desktop step..."
        # Insert your custom Docker Desktop script here (e.g., for local testing or deployment)
        docker run -d -p 80:80 $(containerRegistry)/my-app:$(Build.BuildId)
      displayName: 'Deploy'
